### ISSUE TITLE
Some APNGs are detected as not animated

### ISSUE THREAD

**Issue by zadam** [qzb/is-animated#16]
Hi,

it seems like some of the images are incorrectly detected as not animated (`isAnimated()` returns false), although they are animated. Example: [https://lukeroberts.tv/blog/wp-content/uploads/2019/05/apng1.png](https://lukeroberts.tv/blog/wp-content/uploads/2019/05/apng1.png)

Some other APNGs are working though, such as this: https://irfanview-forum.de/attachment.php?attachmentid=3934&d=1415881419

**Comment by mehmetakify** [comment]
Another sample:

https://www.ionos.com/digitalguide/fileadmin/DigitalGuide/Screenshots_2018/APNG-Beispiel.png
